/*
 * This file is generated by jOOQ.
 */
package com.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser implements Serializable {

    private static final long serialVersionUID = 151452490;

    private Integer       id;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private String        userName;
    private String        password;
    private String        mobile;

    public TUser() {}

    public TUser(TUser value) {
        this.id = value.id;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.userName = value.userName;
        this.password = value.password;
        this.mobile = value.mobile;
    }

    public TUser(
        Integer       id,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        String        userName,
        String        password,
        String        mobile
    ) {
        this.id = id;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.userName = userName;
        this.password = password;
        this.mobile = mobile;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUser (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(userName);
        sb.append(", ").append(password);
        sb.append(", ").append(mobile);

        sb.append(")");
        return sb.toString();
    }
}
