/*
 * This file is generated by jOOQ.
 */
package com.generator;


import com.generator.tables.FlywaySchemaHistory;
import com.generator.tables.TUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq-demo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq-demo.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.generator.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * 用户表
     */
    public static final TUser T_USER = com.generator.tables.TUser.T_USER;
}
